typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/6lrbkxnpym1z8lqrrpg59bwnddxfdc52-zsh-5.9/share/zsh/$ZSH_VERSION/help"

source /nix/store/7103y0q8n75aj611pcfv48sv3nfj2gzd-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git gitignore z)


source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="100000"
SAVEHIST="100000"

HISTFILE="${XDG_DATA_HOME}/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


# Powerlevel10k Zsh theme
source /nix/store/q3r5mc3ypya61bdhqrjpk40vzfmdcx34-powerlevel10k-1.20.15/share/zsh-powerlevel10k/powerlevel10k.zsh-theme
test -f ~/.config/zsh/.p10k.zsh && source ~/.config/zsh/.p10k.zsh

# Direnv hook
eval "$(direnv hook zsh)"

# Key Bindings
# bindkey -s ^t "tmux-sessionizer\n"
# bindkey '^f' "cd $(/nix/store/d8gs5vih8f1nkck5q8jrndzxzdkpsl01-fd-10.2.0/bin/fd . /mnt/work /mnt/work/Projects/ /run/current-system ~/ --max-depth 1 | fzf)\n"
bindkey '^l' "yazi\r"
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# options
unsetopt menu_complete
unsetopt flowcontrol

setopt prompt_subst
setopt always_to_end
setopt append_history
setopt auto_menu
setopt complete_in_word
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

function lf {
    tmp="$(mktemp)"
    # `command` is needed in case `lfcd` is aliased to `lf`
    command lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp"
        if [ -d "$dir" ]; then
            if [ "$dir" != "$(pwd)" ]; then
                cd "$dir"
            fi
        fi
    fi
}
function ex {
 if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
    echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
 else
    for n in "$@"
    do
      if [ -f "$n" ] ; then
          case "${n%,}" in
            *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
            /nix/store/bpn20jn4235mij1372xvpmibgzzpqa3m-gnutar-1.35/bin/tar xvf "$n"       ;;
            *.lzma)      unlzma ./"$n"      ;;
            *.bz2)       bunzip2 ./"$n"     ;;
            *.cbr|*.rar)       unrar x -ad ./"$n" ;;
            *.gz)        gunzip ./"$n"      ;;
            *.cbz|*.epub|*.zip)       unzip ./"$n"       ;;
            *.z)         uncompress ./"$n"  ;;
            *.7z|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
            /nix/store/pi6sy9c50rcl2h8dc8yxhbpc0nfv6lhb-p7zip-17.06/bin/7z x ./"$n"        ;;
            *.xz)        unxz ./"$n"        ;;
            *.exe)       cabextract ./"$n"  ;;
            *.cpio)      cpio -id < ./"$n"  ;;
            *.cba|*.ace)      unace x ./"$n"      ;;
            *)
            echo "Unsupported format"
            return 1
            ;;
          esac
      else
          echo "'$n' - file does not exist"
          return 1
      fi
    done
 fi
}

function fnew {
  if [ -d "$1" ]; then
    echo "Directory \"$1\" already exists!"
    return 1
  fi
  nix flake new $1 --template /nix/store/hzp6n7r7fwhlhcfya7x6kxkhr4ci3pnb-source/dev-shells#$2
  cd $1
  direnv allow
}

function finit {
  nix flake init --template /nix/store/hzp6n7r7fwhlhcfya7x6kxkhr4ci3pnb-source/dev-shells#$1
  direnv allow
}

function cgen {
  if [ -d "$1" ]; then
    echo "Directory \"$1\" already exists!"
    return 1
  fi
  nix flake new $1 --template /nix/store/hzp6n7r7fwhlhcfya7x6kxkhr4ci3pnb-source/dev-shells#c-cpp
  cd $1
  cat ~/.config/zsh/templates/ListTemplate.txt >> CMakeLists.txt
  mkdir src
  mkdir include
  cat ~/.config/zsh/templates/HelloWorldTemplate.txt >> src/main.cpp
  direnv allow
}

function crun {
  #VAR=${1:-.}
  mkdir build 2> /dev/null
  cmake -B build
  cmake --build build
  build/main
}

function cbuild {
  mkdir build 2> /dev/null
  cmake -B build
  cmake --build build
}

function yy() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXX")"
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

source "/nix/store/jy1wmyii4xk90n3bjhrsan5vz3wdld67-wezterm-0-unstable-2025-07-30/etc/profile.d/wezterm.sh"

if [[ $TERM != "dumb" ]]; then
  eval "$(/nix/store/6hq21mqkmdm1ds9974w9xw00blym6fh5-starship-1.23.0/bin/starship init zsh)"
fi

if test -n "$KITTY_INSTALLATION_DIR"; then
  export KITTY_SHELL_INTEGRATION="no-rc"
  autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
  kitty-integration
  unfunction kitty-integration
fi

eval "$(/nix/store/qj6a7xr3knnl5wjs3rvr8ajbjkxbn32f-direnv-2.37.1/bin/direnv hook zsh)"

alias -- att='tmux attach'
alias -- attach='tmux attach'
alias -- bc='bc -ql'
alias -- cls=clear
alias -- cp='cp -iv'
alias -- dev='cd /mnt/work/Projects/'
alias -- dots='cd ~/NixOS/'
alias -- find-store-path='function { nix-shell -p $1 --command "nix eval -f \"<nixpkgs>\" --raw $1" }'
alias -- games='cd /mnt/games/'
alias -- grep='grep --color=always'
alias -- l='/nix/store/n4aac68x6njws1m93zn6wki8nn8h6i1s-eza-0.23.0/bin/eza -lh  --icons=auto'
alias -- ld='/nix/store/n4aac68x6njws1m93zn6wki8nn8h6i1s-eza-0.23.0/bin/eza -lhD --icons=auto'
alias -- lg=lazygit
alias -- list-gens='sudo nix-env --list-generations --profile /nix/var/nix/profiles/system/'
alias -- ll='/nix/store/n4aac68x6njws1m93zn6wki8nn8h6i1s-eza-0.23.0/bin/eza -lha --icons=auto --sort=name --group-directories-first'
alias -- ls='/nix/store/n4aac68x6njws1m93zn6wki8nn8h6i1s-eza-0.23.0/bin/eza -1   --icons=auto'
alias -- media='cd /mnt/work/media/'
alias -- mkd='mkdir -pv'
alias -- mv='mv -iv'
alias -- nf=/nix/store/bd58176d3lx27inlfp7yh57496vd9g8w-microfetch-0.4.9/bin/microfetch
alias -- nv=nvim
alias -- pokemon='pokego --random 1-8 --no-title'
alias -- proj='cd /mnt/work/Projects/'
alias -- projects='cd /mnt/work/Projects/'
alias -- rebuild=/nix/store/dmarad4kmyk43r2bb50lypn3gllzl0jl-rebuild.sh
alias -- rm='rm -vI'
alias -- sysup='sudo nixos-rebuild switch --flake ~/NixOS#Default --upgrade-all --show-trace'
alias -- tml='tmux list-sessions'
alias -- tp=/nix/store/9a959817yr68ip3nhlz1g77gcshcz28k-trash-cli-0.24.5.26/bin/trash-put
alias -- tpr=/nix/store/9a959817yr68ip3nhlz1g77gcshcz28k-trash-cli-0.24.5.26/bin/trash-restore
alias -- tree='/nix/store/n4aac68x6njws1m93zn6wki8nn8h6i1s-eza-0.23.0/bin/eza --icons=auto --tree'
alias -- update-input='nix flake update $@'
alias -- vc='code --disable-gpu'
alias -- work='cd /mnt/work/'
alias -g -- G='| grep'
alias -g -- UUID='$(uuidgen | tr -d \n)'
source /nix/store/34r5z8iyybf3l8wb4i089p489whsmrcz-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=()


