[manager]
linemode = "size"
ratio = [1, 3, 4]
show_hidden = true
show_symlink = true
sort_dir_first = true

[preview]
image_filter = "triangle"
image_quality = 90
max_height = 1080
max_width = 1920
tab_size = 4
